### ISSUE TITLE
Use the new Python 3.10 switch feature to streamline controller choice

### ISSUE THREAD

**Issue by DanielCollishawSchepman** [Joshcolemitchell/python-intermediate-inflammation#10]
In `inflammation-analysis.py`, use Python [switches](https://docs.python.org/3/tutorial/controlflow.html#match-statements) instead of if else statements.

**Comment by grmtrkngtn** [comment]
We want the program to be backwards compatible with previous versions of Python, such as 3.8, and therefore will not be pursuing this feature development.
