### ISSUE TITLE
Add checks to Day values

### ISSUE THREAD

**Issue by wk9874** [Joshcolemitchell/python-intermediate-inflammation#18]
The values of Day linked to an observation should not be allowed to be < 0. Should add a check to confirm that the value inputted is >= 0, and if not it should raise an error.

May also want to decide if more than one observation measurement per day is allowed. If you only want one measurement per day, then another check should be performed to make sure that the Day of the new observation being added does not already exist in an observation for that patient.

**Comment by grmtrkngtn** [comment]
Resolved on Fork

**Comment by xy2973** [comment]
Resolved by GRUKAEA
